### ISSUE TITLE
【ユーザー機能】テーブルを作成する

### ISSUE THREAD

**Issue by polish100** [YujiMiyashita/stack_over_flow#2]
テーブル名
- [x] users

カラム追加
- [x] t.string :uid,      null: false, default: ""
- [x] t.string :provider, null: false, default: “"

index追加
- [x] add_index :users, :email,                unique: true
- [x] add_index :users, :reset_password_token, unique: true
- [x] add_index :users, [:uid, :provider],     unique: true

**Comment by amberloop** [comment]
完了したのでクローズします。
