### ISSUE TITLE
【回答機能】作成機能を実装する

### ISSUE THREAD

**Issue by YujiMiyashita** [YujiMiyashita/stack_over_flow#27]
answers_controllerのcrateアクションに以下を定義する
- [ ] currentに紐付いたanswerのインスタンスを定義し、ストロングパラメータを介して値を取得する
- [ ] question_idをparamsから取得する
- [ ] 保存が成功したら質問の詳細画面へリダイレクトさせる

**Comment by ghost** [comment]
この作業の前に、モデルでの、user：answer、question：answer　のアソシエーションを設定を行ってよろしいでしょうか？
