### ISSUE TITLE
【回答機能】自分の投稿でないと編集・削除できないようにする

### ISSUE THREAD

**Issue by YujiMiyashita** [YujiMiyashita/stack_over_flow#35]
- [ ] edit, update, destroyに適用
- [ ] privateにmy_answerというアクションを定義
- [ ] ログインしているユーザーと回答を投稿したユーザーが等しくない場合
- [ ] 「この操作はできません」というメッセージが表示される
- [ ] 質問の詳細画面へリダイレクトさせる

**Comment by ghost** [comment]
スタックオーバフローは誰の回答でも編集できてしまうようですが、どうしますか?

**Comment by YujiMiyashita** [comment]
フツーでOKです
