### ISSUE TITLE
【質問機能】アソシエーションを定義する

### ISSUE THREAD

**Issue by YujiMiyashita** [YujiMiyashita/stack_over_flow#85]
## 完了条件
- [ ] ユーザーと質問が１：多の関係になるように定義する
- [ ] questionsコントローラのcreateアクションにてuser_idに現在ログインしているユーザーのIDを入れるコードを実装する

**Comment by ghost** [comment]
questionsコントローラのcreateアクションにてuser_idに現在ログインしているユーザーのIDを入れるコードを実装する為、
下記をコンソールで試したのですが、cuurent_user.id を@question.user_id に代入できません。
お手数をおかけしますが、アドバイスをお願いいたします。
（ログインしてuserID取得後に行っています/deviseはインストールしています）

```
[5] pry(main)> @question = Question.new
=> #<Question:0x007ff3f3264ca8
 id: nil,
 title: nil,
 content: nil,
 user_id: nil,
 image: nil,
 contribution: nil,
 created_at: nil,
 updated_at: nil>
[6] pry(main)> @question.user_id = current_user.id
NameError: undefined local variable or method `current_user' for main:Object
from (pry):6:in `<main>'
```

**Comment by YujiMiyashita** [comment]
rails コンソールではcurrent_userというメソッドは使えませんよ。
current_userを使いたいのであれば、pryデバックするのが一番良いかと思います！

**Comment by ghost** [comment]
rails コンソールではcurrent_user等は使えないのですね。
userIDが取得できていないのかと思っていました。。
これからはpryデバックを使います。ご回答ありがとうございました。
