### ISSUE TITLE
【質問機能】画像アップローダーの設定

### ISSUE THREAD

**Issue by YujiMiyashita** [YujiMiyashita/stack_over_flow#91]
## 完了条件

- [ ] アップローダーの設定

- [ ] フォームから画像をアップできるようにする

- [ ] 質問詳細にてその画像を見られるようにする

**Comment by cino3** [comment]
questionsテーブルとanswersテーブルには、すでにimegeカラムがある為、追加できないです。
私は意図を勘違いしてますでしょうか？

**Comment by ghost** [comment]
questionsテーブルとanswersテーブルに既にimageカラムがありました。別のimageカラムを作る予定でしたでしょうか？
